/* eslint-disable  no-unused-vars */
import Character from './Character';
import Bowman from './Bowman';
import Daemon from './Daemon';
import Magician from './Magician';
import Swordsman from './Swordsman';
import Undead from './Undead';
import Zombie from './Zombie';
/* eslint-enable no-unused-vars */
